apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: cesigoodfood/order:1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "200Mi"
            cpu: "700m"
          requests:
            memory: "200Mi"
            cpu: "700m"
      initContainers:
        - name: wait-db
          image: busybox:1.31
          command: ['sh', '-c', "until nslookup mariadb-order-sts-0.order-database-service.default.svc.cluster.local; do echo waiting for mydb; sleep 20; done"]