apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: cesigoodfood/auth:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "200Mi"
            cpu: "700m"
          requests:
            memory: "200Mi"
            cpu: "700m"
      initContainers:
      - name: wait-db
        image: busybox:1.31
        command: ['sh', '-c', "until nslookup mariadb-auth-sts-0.auth-database-service.default.svc.cluster.local; do echo waiting for mydb; sleep 20; done"]