apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-database-configmap
data:

  primary.cnf: |
    [mariadb]
    log-bin                         # enable binary loging
    # We are going to create server_id in initContainer
    # server_id=3000                  # used to uniquely identify the server
    log-basename=my-mariadb         # used to be independent of to hostname changes (otherwise is in datadir/mysql)
    #binlog-format=MIXED            #default
  replica.cnf: |
    [mariadb]
    # We are going to create server_id in initContainer
    # server_id=3001                  # used to uniquely identify the server
    log-basename=my-mariadb         # used to be independent of to hostname changes (otherwise is in datadir/mysql)
    #binlog-format=MIXED            #default
  primary.sql: |
    CREATE USER 'repluser'@'%' IDENTIFIED BY 'replsecret';
    GRANT REPLICATION SLAVE ON *.* TO 'repluser'@'%';
    CREATE DATABASE auth_database;
  secondary.sql: |
    # we have to know name of sts (`mariadb-auth-sts`) and
    # service `auth-database-service` in advance as an FQDN
    CHANGE MASTER TO
    MASTER_HOST='mariadb-auth-sts-0.auth-database-service.default.svc.cluster.local',
    MASTER_USER='repluser',
    MASTER_PASSWORD='replsecret',
    MASTER_PORT=3306,
    MASTER_CONNECT_RETRY=10;